# -*- coding: utf-8 -*-
"""project_trials.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDvExx_iaWxhVnF1EsHNuBFy6SCyrT2X
"""

#nlp
from transformers import T5Tokenizer, T5ForConditionalGeneration

#data
import pandas as pd
import numpy as np



def generate(text, model_path = r'C:\assignments\cs733-nlp\web-page-summarizer\extension\t5-model', tokenizer_path = r'C:\assignments\cs733-nlp\web-page-summarizer\extension\t5-model'):
  tokenizer = T5Tokenizer.from_pretrained(model_path, return_tensors = 'pt')
  model = T5ForConditionalGeneration.from_pretrained(tokenizer_path, return_dict = True)
  model.eval()
  input_ids = tokenizer.encode(text, return_tensors = 'pt')
  outputs = model.generate(input_ids)
  return tokenizer.decode(outputs[0]).strip('<pad>').strip('</s>').strip()

if __name__ == '__main__':
  # print(generate('flights | action | search && flights | region | top_left').strip('<pad>').strip('</s>'))

  # print(generate('flights |  action  | filter && flights | region | left'))

  # test_df = pd.read_csv('/content/drive/MyDrive/t5-model/web_dataset2.csv', index_col = [0])
  # test_df = test_df[['model_input','description']]



  # test_df['model_output'] = test_df['model_input'].map(lambda text: generate(text))
  # test_df

  # similar model_output and description out of total number of rows.
  # sum((test_df['model_output'].map(lambda row: row.strip().lower()) == test_df['description'].map(lambda row: row.strip().lower())).astype('int')) / len(test_df)

  print(generate('animals | action | filter && animals | location | center'))
  print(generate('flight | action | locate flights && flights | location | bottom-right'))